Repository TikitakaDiary/MemoryTrace-Android, pull requests merged in 2021-05, with the labels that each got.

#30 [전체] 폰트 및 여백 스타일 가이드 적용
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: Feature, Refactor

#31 [전체] 이미지 크롭 라이브러리 추가
  app/build.gradle
  build.gradle
  cropper/build.gradle
  cropper/src/main/AndroidManifest.xml
  cropper/src/main/java/com/theartofdev/edmodo/cropper/BitmapCroppingWorkerTask.java
  cropper/src/main/java/com/theartofdev/edmodo/cropper/BitmapLoadingWorkerTask.java
  cropper/src/main/java/com/theartofdev/edmodo/cropper/BitmapUtils.java
  cropper/src/main/java/com/theartofdev/edmodo/cropper/CropImage.java
  cropper/src/main/java/com/theartofdev/edmodo/cropper/CropImageActivity.java
  cropper/src/main/java/com/theartofdev/edmodo/cropper/CropImageAnimation.java
  cropper/src/main/java/com/theartofdev/edmodo/cropper/CropImageOptions.java
  cropper/src/main/java/com/theartofdev/edmodo/cropper/CropImageView.java
  cropper/src/main/java/com/theartofdev/edmodo/cropper/CropOverlayView.java
  cropper/src/main/java/com/theartofdev/edmodo/cropper/CropWindowHandler.java
  cropper/src/main/java/com/theartofdev/edmodo/cropper/CropWindowMoveHandler.java
  cropper/src/main/res/drawable-hdpi/crop_image_menu_flip.png
  cropper/src/main/res/drawable-hdpi/crop_image_menu_rotate_left.png
  cropper/src/main/res/drawable-hdpi/crop_image_menu_rotate_right.png
  cropper/src/main/res/drawable-xhdpi/crop_image_menu_flip.png
  cropper/src/main/res/drawable-xhdpi/crop_image_menu_rotate_left.png
  cropper/src/main/res/drawable-xhdpi/crop_image_menu_rotate_right.png
  cropper/src/main/res/drawable-xxhdpi/crop_image_menu_flip.png
  cropper/src/main/res/drawable-xxhdpi/crop_image_menu_rotate_left.png
  cropper/src/main/res/drawable-xxhdpi/crop_image_menu_rotate_right.png
  cropper/src/main/res/drawable-xxxhdpi/crop_image_menu_flip.png
  cropper/src/main/res/drawable-xxxhdpi/crop_image_menu_rotate_left.png
  cropper/src/main/res/drawable-xxxhdpi/crop_image_menu_rotate_right.png
  cropper/src/main/res/layout/crop_image_activity.xml
  cropper/src/main/res/layout/crop_image_view.xml
  cropper/src/main/res/menu/crop_image_menu.xml
  cropper/src/main/res/values/attrs.xml
  cropper/src/main/res/values/strings.xml
  settings.gradle
Labels: Simple, 유진진

#32 [일기장 목록] 화면 및 기능 구현
  app/src/main/java/com/upf/memorytrace_android/api/BaseResponse.kt
  app/src/main/java/com/upf/memorytrace_android/api/MemoryTraceService.kt
  app/src/main/java/com/upf/memorytrace_android/api/model/BookModel.kt
  app/src/main/java/com/upf/memorytrace_android/api/repository/BookRepository.kt
  app/src/main/java/com/upf/memorytrace_android/api/util/AuthHeaderInterceptor.kt
  app/src/main/java/com/upf/memorytrace_android/api/util/NetworkState.kt
  app/src/main/java/com/upf/memorytrace_android/ui/book/BookListAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/ui/book/BookListFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/book/BookViewHolder.kt
  app/src/main/java/com/upf/memorytrace_android/util/Collections.kt
  app/src/main/java/com/upf/memorytrace_android/util/Colors.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/BookListViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/LoginViewModel.kt
  app/src/main/res/drawable/ic_add_diary.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/layout/fragment_book_list.xml
  app/src/main/res/layout/item_book_list.xml
  app/src/main/res/navigation/nav.xml
  app/src/main/res/values/strings.xml
Labels: Feature, Review Needed

#33 [일기장] 일기장 생성 화면 및 기능 구현
  app/src/main/java/com/upf/memorytrace_android/api/MemoryTraceService.kt
  app/src/main/java/com/upf/memorytrace_android/api/model/BookModel.kt
  app/src/main/java/com/upf/memorytrace_android/api/repository/BookRepository.kt
  app/src/main/java/com/upf/memorytrace_android/ui/book/CreateBookFragment.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/CreateBookViewModel.kt
  app/src/main/res/drawable/ic_circle.xml
  app/src/main/res/drawable/ic_circle_border.xml
  app/src/main/res/layout/fragment_create_book.xml
  app/src/main/res/layout/item_color_list.xml
Labels: Feature, Review Needed
