Repository TikitakaDiary/MemoryTrace-Android, pull requests merged in 2021-04, with the labels that each got.

#6 [전체] Base코드 일부 수정 및 Base코드 적용 예시 코드
  app/build.gradle
  app/src/main/java/com/upf/memorytrace_android/base/BaseActivity.kt
  app/src/main/java/com/upf/memorytrace_android/base/BaseFragment.kt
  app/src/main/java/com/upf/memorytrace_android/di/ActivityComponent.kt
  app/src/main/java/com/upf/memorytrace_android/di/AppComponent.kt
  app/src/main/java/com/upf/memorytrace_android/di/FragmentComponent.kt
  app/src/main/java/com/upf/memorytrace_android/di/SubComponentModule.kt
  app/src/main/java/com/upf/memorytrace_android/ui/LoginFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/SplashFragment.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/LoginViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/MainViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/SplashViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/navigation/nav.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: Feature, Merge Needed, Refactor

#10 [전체] 통신 모듈 및 샘플코드 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/upf/memorytrace_android/MemoryTraceApplication.kt
  app/src/main/java/com/upf/memorytrace_android/api/BaseResponse.kt
  app/src/main/java/com/upf/memorytrace_android/api/MemoryTraceService.kt
  app/src/main/java/com/upf/memorytrace_android/api/model/BookModel.kt
  app/src/main/java/com/upf/memorytrace_android/api/model/InviteModel.kt
  app/src/main/java/com/upf/memorytrace_android/api/model/UserModel.kt
  app/src/main/java/com/upf/memorytrace_android/api/repository/BookRepository.kt
  app/src/main/java/com/upf/memorytrace_android/api/util/AuthHeaderInterceptor.kt
  app/src/main/java/com/upf/memorytrace_android/api/util/MemoryTraceUtils.kt
  app/src/main/java/com/upf/memorytrace_android/api/util/NetworkState.kt
  app/src/main/java/com/upf/memorytrace_android/di/ActivityComponent.kt
  app/src/main/java/com/upf/memorytrace_android/di/AppComponent.kt
  app/src/main/java/com/upf/memorytrace_android/di/FragmentComponent.kt
  app/src/main/java/com/upf/memorytrace_android/di/NetworkModule.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/LoginViewModel.kt
  build.gradle
Labels: Review Needed

#11 [전체] 유틸성 코드 추가
  app/src/main/java/com/upf/memorytrace_android/extension/ContextExtension.kt
  app/src/main/java/com/upf/memorytrace_android/util/CloseBackPressed.kt
  app/src/main/java/com/upf/memorytrace_android/util/ViewUtils.kt
  app/src/main/res/values/strings.xml
Labels: Review Needed

#17 [전체] 스티커 모듈 추가
  sticker/src/main/java/com/xiaopo/flying/sticker/BitmapStickerIcon.java
  sticker/src/main/java/com/xiaopo/flying/sticker/DrawableSticker.java
  sticker/src/main/java/com/xiaopo/flying/sticker/Sticker.java
  sticker/src/main/java/com/xiaopo/flying/sticker/StickerUtils.java
  sticker/src/main/java/com/xiaopo/flying/sticker/StickerView.java
  sticker/src/main/java/com/xiaopo/flying/sticker/TextSticker.java
Labels: Feature, Merge Needed, 유진진
