Repository TikitakaDiary/MemoryTrace-Android, pull requests merged in 2021-06, with the labels that each got.

#35 [크롭] UI 반영 및 기능 추가
  app/build.gradle
  app/src/main/java/com/upf/memorytrace_android/ui/CropFragment.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/CropViewModel.kt
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/layout/fragment_crop.xml
  app/src/main/res/navigation/nav.xml
  app/src/main/res/values/strings.xml
Labels: Feature, 유진진

#34 [로그인] 소셜 로그인 구현
  app/build.gradle
  app/google-services.json
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/upf/memorytrace_android/MemoryTraceApplication.kt
  app/src/main/java/com/upf/memorytrace_android/api/BaseResponse.kt
  app/src/main/java/com/upf/memorytrace_android/api/MemoryTraceService.kt
  app/src/main/java/com/upf/memorytrace_android/api/model/UserModel.kt
  app/src/main/java/com/upf/memorytrace_android/api/repository/UserRepository.kt
  app/src/main/java/com/upf/memorytrace_android/api/util/AuthHeaderInterceptor.kt
  app/src/main/java/com/upf/memorytrace_android/ui/LoginFragment.kt
  app/src/main/java/com/upf/memorytrace_android/util/MemoryTraceConfig.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/LoginViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/SplashViewModel.kt
  app/src/main/res/drawable/rect_white_rounded.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/navigation/nav.xml
  app/src/main/res/values/keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: Feature, Review Needed

#36 [일기장 목록] UI개선
  app/src/main/java/com/upf/memorytrace_android/api/repository/BookRepository.kt
  app/src/main/java/com/upf/memorytrace_android/ui/book/BookListAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/ui/book/BookListFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/book/BookViewHolder.kt
  app/src/main/res/layout/fragment_book_list.xml
  app/src/main/res/values/strings.xml
Labels: Feature, Simple

#37 [일기] 일기의 목록 화면 구현
  app/src/main/java/com/upf/memorytrace_android/base/BaseListAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryDateItem.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryFrameAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryFrameListViewHolder.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryGridAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryGridListViewHolder.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryItem.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryListOfMonthAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryListType.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryMonthItem.kt
  app/src/main/java/com/upf/memorytrace_android/util/TimeUtil.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/DiaryViewModel.kt
  app/src/main/res/drawable/bg_diary_write_button.xml
  app/src/main/res/drawable/ic_frame.xml
  app/src/main/res/drawable/ic_grid.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/item_diary_frame.xml
  app/src/main/res/layout/item_diary_frame_list.xml
  app/src/main/res/layout/item_diary_grid.xml
  app/src/main/res/layout/item_diary_grid_list.xml
  app/src/main/res/layout/item_diary_write_button.xml
  app/src/main/res/layout/view_diary_date.xml
  app/src/main/res/navigation/nav.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Feature, 유진진

#39 [일기] 일기의 목록 화면 구현
  app/build.gradle
  app/src/main/java/com/upf/memorytrace_android/binding/ViewBindingAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/DiaryViewModel.kt
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/item_diary_frame.xml
  app/src/main/res/layout/item_diary_frame_list.xml
  app/src/main/res/layout/item_diary_grid.xml
  app/src/main/res/layout/item_diary_grid_list.xml
  app/src/main/res/navigation/nav.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: Feature, 유진진

#40 [마이페이지] 마이페이지 구현
  app/src/main/java/com/upf/memorytrace_android/api/MemoryTraceService.kt
  app/src/main/java/com/upf/memorytrace_android/api/model/InviteModel.kt
  app/src/main/java/com/upf/memorytrace_android/api/model/UserModel.kt
  app/src/main/java/com/upf/memorytrace_android/api/repository/UserRepository.kt
  app/src/main/java/com/upf/memorytrace_android/ui/LoginFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/MakersFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/MypageFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/NameEditFragment.kt
  app/src/main/java/com/upf/memorytrace_android/util/MemoryTraceConfig.kt
  app/src/main/java/com/upf/memorytrace_android/util/ViewUtils.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/BookListViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/MakersViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/MypageViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/NameEditViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/SplashViewModel.kt
  app/src/main/res/drawable/ic_google.xml
  app/src/main/res/drawable/ic_kakaotalk.xml
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/drawable/rect_gray_rounded.xml
  app/src/main/res/drawable/rect_white_rounded_22.xml
  app/src/main/res/layout/fragment_book_list.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_makers.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_name_edit.xml
  app/src/main/res/mipmap-xhdpi/sample_makers.png
  app/src/main/res/navigation/nav.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Feature, Review Needed

#41 [작성하기] 일기 작성하기 기능 구현
  app/build.gradle
  app/src/main/java/com/upf/memorytrace_android/base/BaseViewPagerFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/ColorAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/ColorItem.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/ColorViewHolder.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/StickerAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/StickerItem.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/StickerSlidePagerAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/WriteColorBottomSheetFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/WriteFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/WriteImageBottomSheetFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/WriteStickerBottomSheetFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/WriteStickerFragment.kt
  app/src/main/java/com/upf/memorytrace_android/util/Colors.kt
  app/src/main/java/com/upf/memorytrace_android/util/ImageConverter.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/WriteViewModel.kt
  app/src/main/res/drawable/bg_bottom_sheet_write.xml
  app/src/main/res/layout/fragment_bottom_sheet_write_color.xml
  app/src/main/res/layout/fragment_bottom_sheet_write_image.xml
  app/src/main/res/layout/fragment_bottom_sheet_write_sticker.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/fragment_write_sticker.xml
  app/src/main/res/layout/item_color.xml
  app/src/main/res/layout/item_sticker.xml
  app/src/main/res/navigation/nav.xml
  app/src/main/res/values/strings.xml
Labels: Feature, 유진진

#43 [전체] 화면 연결 및 API 연결
  app/src/main/java/com/upf/memorytrace_android/api/BaseResponse.kt
  app/src/main/java/com/upf/memorytrace_android/api/MemoryTraceService.kt
  app/src/main/java/com/upf/memorytrace_android/api/model/DiaryModel.kt
  app/src/main/java/com/upf/memorytrace_android/api/repository/DiaryRepository.kt
  app/src/main/java/com/upf/memorytrace_android/ui/DetailFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/book/BookListAdapter.kt
  app/src/main/java/com/upf/memorytrace_android/ui/book/BookListFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/book/BookViewHolder.kt
  app/src/main/java/com/upf/memorytrace_android/ui/diary/DiaryFragment.kt
  app/src/main/java/com/upf/memorytrace_android/ui/write/WriteFragment.kt
  app/src/main/java/com/upf/memorytrace_android/util/ImageConverter.kt
  app/src/main/java/com/upf/memorytrace_android/util/TimeUtil.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/BookListViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/DetailViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/DiaryViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/LoginViewModel.kt
  app/src/main/java/com/upf/memorytrace_android/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_diary.xml
  app/src/main/res/layout/fragment_write.xml
  app/src/main/res/layout/item_diary_frame.xml
  app/src/main/res/layout/item_diary_grid.xml
  app/src/main/res/navigation/nav.xml
Labels: Feature, Review Needed, 유진진
